### ISSUE TITLE
asset requests you need: tell me here ★

### ISSUE THREAD

**Issue by isadeu** [JohnWubdub/Final_Project#13]

**Comment by isadeu** [comment]
one for each 3 areas 👍🏼
fighting minagame = boxing ring 
menu 
hiccup 
press

**Comment by isadeu** [comment]
probably can be inspired for the huccip and the menu one from the actual game

**Comment by JohnWubdub** [comment]
We need a podium, that silhouette character, and I think that's it for minigame 4
