### ISSUE TITLE
Design Tutorials

### ISSUE THREAD

**Issue by JohnWubdub** [JohnWubdub/Final_Project#166]

**Comment by JohnWubdub** [comment]
Prompt, Controls

**Comment by JohnWubdub** [comment]
99 Hiccups, SPACE

**Comment by JohnWubdub** [comment]
Combo Breaker, WASD

**Comment by JohnWubdub** [comment]
Try to Run, ASD + SPACE to switch

**Comment by JohnWubdub** [comment]
The Right Press, AD + SPACE

**Comment by JohnWubdub** [comment]
Touch Her, WASD to Move

**Comment by valanars** [comment]
for the 99 hiccups, maybe do "hold or press space to hiccup" and for try to run "space to switch character" ???? the rest are pretty simple + self explanatory, so i think that's good
